project/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, StringField, PasswordField, SubmitField, DateField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class RegisterForm(FlaskForm):
    first_name = StringField("First Name", validators=[DataRequired(), Length(min=3, max=12)])
    last_name = StringField("Last Name", validators=[DataRequired(), Length(min=3, max=12)])
    birthday  = DateField('Birthdate',format='%Y-%m-%d')
    gender = RadioField("Gender", choices=[("Male", 'Male'), ("Female", "Female")], default="Male", validators=[DataRequired()])
    email_address = StringField("Email Address", validators=[DataRequired(), Email(), ])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=6, max=12)])
    confirm_password = PasswordField("Password", validators=[DataRequired(), Length(min=6, max=12), EqualTo('password')])
    submit = SubmitField("Register")


class LoginForm(FlaskForm):
    email_address = StringField("Email Address", validators=[DataRequired(), Email() ])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=6, max=12)])
    submit = SubmitField("Login")

project/__init__.py
from flask import Flask
import secrets

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = secrets.token_hex(5)

    from project.routes import views

    app.register_blueprint(views)

    return app

project/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from project.forms import RegisterForm, LoginForm

views = Blueprint("views", __name__)

@views.route("/")
@views.route("/home")
def home():
    return render_template("home.html")

@views.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        if form.email_address.data == "jhonielvillacura04@gmail.com" and form.password.data == "potanginamo":
            flash(f"Welcome back sir", "success")
            return redirect(url_for('views.home'))
        else:
            flash(f"Wrong data sorry", "danger")

    return render_template("login.html", form=form)

@views.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit(): 
        flash(f"You can now logged in!", "success")
        return redirect(url_for('views.login'))
     
    return render_template("register.html", form=form)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/css/bootstrap.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/css/index.css')}}"
    />

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Flask Activty</title>
    {% endif %}
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Flask Project</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.login') }}"
                  >Login</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.register') }}"
                  >Create</a
                >
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="container w-full h-full mt-3 py-2">
      <div class="row">
        <div class="col-md-9">{% block content %}{% endblock %}</div>
        <div class="col-md-3">
          <div class="card shadow p-3">
            <h4 class="card-title">Boostrap Offline!</h4>
            <div class="card-body list-group">
              <li class="list-group-item">Hello World</li>
              <li class="list-group-item">Hello World</li>
              <li class="list-group-item">Hello World</li>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

project/templates/home.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages(with_categories=true) %} {% if messages %} {% for category,
message in messages %}
<p class="alert text-sm alert-{{ category }}">{{ message }}</p>
{% endfor %} {% endif %} {% endwith %}

<div class="card shadow p-3">
  <p class="card-title">Hello Home</p>
</div>
{% endblock %}

project/templates/login.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages(with_categories=true) %} {% if messages %} {% for category,
message in messages %}
<p class="alert text-sm alert-{{ category }}">{{ message }}</p>
{% endfor %} {% endif %} {% endwith %}

<div class="form-group shadow p-4">
  <h3 class="text-dark mb-5">Login Account</h3>

  <form method="post">
    {{ form.hidden_tag() }}
    <div class="form-group pb-2">
      {{ form.email_address.label(class="form-control-label") }} {{
      form.email_address(class="form-control form-control-md") }}
    </div>
    <div class="form-group pb-2">
      {{ form.password.label(class="form-control-label") }} {{
      form.password(class="form-control form-control-md") }}
    </div>
    <div class="form-group pt-2">
      {{ form.submit(class="btn btn-outline-dark") }}
    </div>
  </form>
</div>

{% endblock %}

project/templates/register.html
{% extends "base.html" %} {% block content %}

<div class="register-container p-4 border shadow">
  <h3 class="text-dark">Register Now!</h3>
  <form method="post" class="form-group">
    {{ form.hidden_tag() }}

    <div class="row">
      <div class="col-md-6 form-group p-2">
        {{ form.first_name.label(class="form-control-label") }} {{
        form.first_name(class="form-control form-control-md") }}
      </div>
      <div class="col-md-6 form-group p-2">
        {{ form.last_name.label(class="form-control-label") }} {{
        form.last_name(class="form-control form-control-md") }}
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 form-group p-2">
        {{ form.birthday.label(class="form-control-label") }} {{
        form.birthday(class="form-control form-control-md") }}
      </div>
      <div class="col-md-6 form-group">
        <p>Gender</p>
        {% for radio in form.gender %}
        <div class="form-check">
          {{ radio.label(class="form-check-label") }} {{
          radio(class="form-check-input") }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 form-group p-2">
        {{ form.email_address.label(class="form-control-label") }} {{
        form.email_address(class="form-control form-control-md") }}
      </div>
      <div class="col-md-12 form-group p-2">
        {{ form.password.label(class="form-control-label") }} {{
        form.password(class="form-control form-control-md") }}
      </div>
      <div class="col-md-12 form-group p-2">
        {{ form.confirm_password.label(class="form-control-label") }} {{
        form.confirm_password(class="form-control form-control-md") }}
      </div>
      <div class="form-group col-md-3 p-2">
        {{ form.submit(class="btn btn-outline-dark")}}
      </div>
    </div>
  </form>
  <div class="d-flex gap-3 mt-3">
    <p class="text-sm text-seconday">Already have an account?</p>
    <a href="#" class="text-primary text-sm">Log in here</a>
  </div>
</div>

{% endblock %}